<?php
    DEFINE('STATUS',  array("OK"=>"0", "NOT_FOUND"=>"1", "DB_FAILED"=>"2", "JUMUIYA_DEACTIVATED"=>"3", "ADD_USER_FAILED"=>"4", "ADD_USER_PRIVILEGE_OCCUPATION_FAILED"=>"5", "USERID_EXISTS"=>"6", "USER_DEACTIVATED"=>"7"));
    DEFINE('CONTRSTATUS',  array("RECEIVED"=>"0", "PENDING"=>"1", "DENIED"=>"2"));
    DEFINE('CONTRTYPEACCESS',  array("READANDWRITE"=>"0", "READONLY"=>"1", "WRITEONLY"=>"2"));
    DEFINE('JUMUIYASTATUS',  array("ACTIVATED"=>"0", "DEACTIVATED"=>"1"));
    DEFINE('MASSSTATUS',  array("ACTIVATED"=>"0", "DEACTIVATED"=>"1"));
    DEFINE('CONTRTYPESTATUS',  array("ACTIVATED"=>"0", "DEACTIVATED"=>"1"));
    DEFINE('USERSTATUS',  array("ACTIVATED"=>"0", "DEACTIVATED"=>"1"));
?>
